version: '2'
services:
  indice-pobreza:
    container_name: indice-pobreza
    build:
      context: docker-indice-pobreza
      dockerfile: Dockerfile
    image: indice-pobreza:latest
    ports:
      - 18888:8080
    networks:
      - spring-cloud-network
  product-server:
    container_name: product-server
    build:
      context: docker-product-server
      dockerfile: Dockerfile
    image: product-server:latest
    ports:
      - 19999:9090
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge